<a href="https://colab.research.google.com/github/rajatktiwari/Deep-Learning/blob/main/Word_embedding_Exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow

In [ ]:
import keras

In [ ]:
from keras.preprocessing.text import one_hot

In [ ]:
sent = [ 'a glass of wine ',
        'a glass of wishkey',
        'I am a ood boy',
        'I love to play Basketball',
        'I love Data Science ',
        'Machines are good',
        'Coding is hard']

In [ ]:
voc_size = 10000

In [ ]:
onehot_repr = [one_hot(words,voc_size)for words in sent]

In [ ]:
print(onehot_repr)

[[6894, 2746, 3101, 2939], [6894, 2746, 3101, 476], [2095, 6320, 6894, 5040, 6557], [2095, 350, 2978, 584, 3740], [2095, 350, 7121, 5497], [8664, 1662, 7008], [9689, 1092, 8613]]


In [ ]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import numpy as np


In [ ]:
sent_length = 8

In [ ]:
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6894 2746 3101 2939]
 [   0    0    0    0 6894 2746 3101  476]
 [   0    0    0 2095 6320 6894 5040 6557]
 [   0    0    0 2095  350 2978  584 3740]
 [   0    0    0    0 2095  350 7121 5497]
 [   0    0    0    0    0 8664 1662 7008]
 [   0    0    0    0    0 9689 1092 8613]]


In [ ]:
dim= 10

In [ ]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs)[0])

[[ 0.01446346  0.02486709  0.00455066  0.03522796 -0.03081334 -0.02201868
  -0.02807215 -0.00498087 -0.00459971  0.00751288]
 [ 0.01446346  0.02486709  0.00455066  0.03522796 -0.03081334 -0.02201868
  -0.02807215 -0.00498087 -0.00459971  0.00751288]
 [ 0.01446346  0.02486709  0.00455066  0.03522796 -0.03081334 -0.02201868
  -0.02807215 -0.00498087 -0.00459971  0.00751288]
 [ 0.01446346  0.02486709  0.00455066  0.03522796 -0.03081334 -0.02201868
  -0.02807215 -0.00498087 -0.00459971  0.00751288]
 [-0.03514725  0.00825701  0.04398259 -0.01790708  0.03102628 -0.01022221
   0.00762241 -0.01767483  0.04212772 -0.04960465]
 [ 0.00165381  0.00378577  0.03711578  0.01630041  0.00359392  0.01234848
   0.02016797  0.03053123  0.01652848  0.02864099]
 [ 0.00845152 -0.02267201 -0.03128042 -0.01967578  0.02906423 -0.04456238
  -0.04550656 -0.00019518 -0.01301737  0.03683012]
 [-0.02610412 -0.04539371  0.00369228  0.00934832 -0.03718008  0.03002865
   0.00118209 -0.0141461  -0.00470937 -0.02857039]]